### ISSUE TITLE
Import component is not working

### ISSUE THREAD

**Issue by ghost** [vuejs-templates/browserify-simple#10]
```
Component template should contain exactly one root element:                                                                            

Menu                                                                                                                                   

Error: Vue template compilation failed while parsing file: C:\Workspace\vue\my-project\src\Menu.vue                                    
    at compileTemplate (C:\Workspace\vue\my-project\node_modules\vueify\lib\template-compiler.js:10:11)                                
    at C:\Workspace\vue\my-project\node_modules\vueify\lib\compiler.js:243:24                                                          
    at process._tickCallback (internal/process/next_tick.js:103:7)                                                                     
Error: Cannot find module './Menu' from 'C:\Workspace\vue\my-project\src'                                                              
Error: Cannot find module 'Menu' from 'C:\Workspace\vue\my-project\src'
```

**Comment by chrisvfritz** [comment]
The error seems pretty clear. Are you importing a component that contains more than one root node?

**Comment by ghost** [comment]
**See how is my project**
![error](https://cloud.githubusercontent.com/assets/16508494/18130190/034950fa-6f5c-11e6-9eaa-a20389bc8de0.png)

**Comment by zigomir** [comment]
@leonardosoares yep, you'll need to wrap `Menu` word in html tag ;)

**Comment by ghost** [comment]
But have html tag in App.vue `<menu></menu>`

**Comment by chrisvfritz** [comment]
@leonardosoares Look at `Menu.vue`. The template should not have a text node (`Menu`) at the root, but a component or HTML element.

**Comment by Jiiiiiin** [comment]
一个模板下面建议只放置一个根节点

**Comment by SuperChrisliu** [comment]
@Jiiiiiin 两个就出错了。。。
