### ISSUE TITLE
Syntax Error creating project

### ISSUE THREAD

**Issue by mstaack** [vuejs-templates/browserify-simple#5]
whats wrong here?

```
➜  ~  vue init browserify-simple demo      

/usr/lib/node_modules/vue-cli/node_modules/metalsmith/lib/index.js:190
Metalsmith.prototype.build = unyield(function*(){
                                             ^
SyntaxError: Unexpected token *
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/vue-cli/node_modules/metalsmith/index.js:6:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
➜  ~  npm -v
3.7.2
➜  ~  uname -a
Linux max-OptiPlex-790 3.19.0-58-generic #64~14.04.1-Ubuntu SMP Fri Mar 18 19:05:43 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by yyx990803** [comment]
`vue-cli` uses ES6 Generators, it seems you are using a very old version of Node that doesn't support.

It's recommended to upgrade to Node v4+.
